Fixed the init script for debian to work properly.

diff --git a/src/deb/init.d/midolmanj b/src/deb/init.d/midolmanj
--- a/src/deb/init.d/midolmanj
+++ b/src/deb/init.d/midolmanj
@@ -11,106 +11,166 @@
 # Short-Description:	Midokura MidolmanJ server
 ### END INIT INFO
 
-set -e
+# Do NOT "set -e"
 
 # /etc/init.d/midolmanj: start and stop the MidolmanJ daemon
 
+MIDO_HOME=/usr/share/midolman
+MIDO_ETC=/etc/midolman
+MIDO_MAIN=com.midokura.midolman.Midolman
+# FIXME(tfukushima): Remove hard coded version number.
+MIDO_JAR=$MIDO_HOME/midolmanj-0.1.0-SNAPSHOT.jar
+MIDO_CFG=$MIDO_ETC/midolman.conf
+MIDO_LOG_DIR=/var/midolman/log
+
+# Exit if the package is not installed
+# Test that midolmanj is installed
+[ -r $MIDO_JAR ] || exit 0
+# Test that midolmanj installed and not purged
+[ -r $MIDO_CFG ] || exit 0
 umask 022
+. $MIDO_ETC/midolman-env.sh
 
-. /usr/libexec/zkEnv.sh
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Midolman: OpenFlow-based network controller"
+SCRIPTNAME=/etc/init.d/$NAME
 
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
-ZOOPIDFILE=/var/lib/zookeeper/data/zookeeper_server.pid
-
-# Are we running from init?
-run_by_init() {
-    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
+is_running()
+{
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $JAVA \
+      --user $USER --test > /dev/null \
+		|| return 1
+    return 0
 }
 
-check_for_no_start() {
-    # forget it if we're trying to start, and /etc/zookeeper/zookeeper_not_to_be_run exists
-    if [ -e /etc/zookeeper/zookeeper_not_to_be_run ]; then 
-	if [ "$1" = log_end_msg ]; then
-	    log_end_msg 0
-	fi
-	if ! run_by_init; then
-	    log_action_msg "Apache ZooKeeper server not in use (/etc/zookeeper/zookeeper_not_to_be_run)"
-	fi
-	exit 0
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+    echo -n "Starting midolmanj... "
+    # Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+    is_running || return 1
+    
+    if [ ! -d $PIDDIR ]
+    then
+      mkdir -p $PIDDIR
     fi
+    chown $USER:$GROUP $PIDDIR
+
+    if [ ! -d  $MIDO_LOG_DIR ]
+    then
+      mkdir -p $MIDO_LOG_DIR
+    fi
+    chown $USER:$GROUP $MIDO_LOG_DIR
+
+	start-stop-daemon --start --quiet \
+               --pidfile $PIDFILE \
+               --make-pidfile \
+               --chuid $USER:$GROUP \
+               --background \
+               --exec $JAVA -- \
+                 -cp $MIDO_ETC:$MIDO_JAR \
+                 $JAVA_OPTS \
+                 $MIDO_MAIN \
+                 -c $MIDO_CFG \
+		|| return 2
+    echo "done"
 }
 
-export PATH="${PATH:+$PATH:}/usr/sbin:/usr/bin"
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    echo -n "Stopping midolmanj... "
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	is_running && return 1
+
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+    echo "done"
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	[ "$RETVAL" = 0 ] && rm -f $PIDFILE
+	return "$RETVAL"
+}
 
 case "$1" in
   start)
-	check_for_no_start
-	log_daemon_msg "Starting Apache ZooKeeper server" "zookeeper"
-	if start-stop-daemon --start --quiet --oknodo --pidfile ${ZOOPIDFILE} -c zookeeper -x ${ZOOKEEPER_PREFIX}/sbin/zkServer.sh start; then
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
+        if [ "x$JMXDISABLE" = "x" ]
+        then
+            [ "$VERBOSE" != no ] && log_action_msg "$NAME: JMX enabled by default"
+            # for some reason these two options are necessary on jdk6 on Ubuntu
+            #   accord to the docs they are not necessary, but otw jconsole cannot
+            #   do a local attach
+            JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=$JMXLOCALONLY"
+        else
+            [ "$VERBOSE" != no ] && log_action_msg "$NAME: JMX disabled by user request"
+        fi
+
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   stop)
-	log_daemon_msg "Stopping Apache ZooKeeper server" "zookeeper"
-	if start-stop-daemon --stop --quiet --oknodo --pidfile ${ZOOPIDFILE}; then
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
-
-  restart)
-	check_privsep_dir
-	log_daemon_msg "Restarting Apache ZooKeeper server" "zookeeper"
-	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile ${ZOOPIDFILE}
-	check_for_no_start log_end_msg
-	if start-stop-daemon --start --quiet --oknodo --pidfile ${ZOOPIDFILE} -c zookeeper -x ${ZOOKEEPER_PREFIX}/bin/zkServer.sh start; then
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
-	;;
-
-  try-restart)
-	check_privsep_dir
-	log_daemon_msg "Restarting Apache ZooKeeper server" "zookeeper"
-	set +e
-	start-stop-daemon --stop --quiet --retry 30 --pidfile ${ZOOPIDFILE}
-	RET="$?"
-	set -e
-	case $RET in
-	    0)
-		# old daemon stopped
-		check_for_no_start log_end_msg
-		if start-stop-daemon --start --quiet --oknodo --pidfile ${ZOOPIDFILE} -c zookeeper -x ${ZOOKEEPER_PREFIX}/bin/zkServer.sh start; then
-		    log_end_msg 0
-		else
-		    log_end_msg 1
-		fi
+  status)
+       status_of_proc -p $PIDFILE "$NAME" "$NAME" && exit 0 || exit $?
+       ;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
 		;;
-	    1)
-		# daemon not running
-		log_progress_msg "(not running)"
-		log_end_msg 0
-		;;
-	    *)
-		# failed to stop
-		log_progress_msg "(failed to stop)"
+	  *)
+	  	# Failed to stop
 		log_end_msg 1
 		;;
 	esac
 	;;
-
-  status)
-	status_of_proc -p ${ZOOPIDFILE} ${JAVA_HOME}/bin/java zookeeper && exit 0 || exit $?
-	;;
-
   *)
-	log_action_msg "Usage: /etc/init.d/midolmanj {start|stop|restart|try-restart|status}"
-	exit 1
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit 0
+:
