Java 1.8 support for devmido
Devmido installs java 1.8 now that midonet only runs on java 1.8.
Also, the midonet scripts were updated to allow the base midolman
directory to be set from outside which is needed to be able to run
prepare_java from these scripts.

Change-Id: Ibf199fab9708c9097bfbd0b2c9068b2fd7ff6e65
Fixes: MNA-741
Signed-off-by: Ryu Ishimoto <ryu@midokura.com>

diff --git a/midolman/src/deb/bin/mm-ctl b/midolman/src/deb/bin/mm-ctl
--- a/midolman/src/deb/bin/mm-ctl
+++ b/midolman/src/deb/bin/mm-ctl
@@ -14,13 +14,6 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-if [ -f /usr/share/midolman/prepare-java ]; then
-    . /usr/share/midolman/prepare-java
-else
-    echo "/usr/share/midolman/prepare-java: file not found"
-    exit 1
-fi
-
 # If MIDO_HOME has not been set, set it.
 if [ -z "$MIDO_HOME" ]; then
    MIDO_HOME=/usr/share/midolman
@@ -29,6 +22,13 @@ fi
 if [ ! -d "$MIDO_HOME" ]; then
    echo "ERROR: $MIDO_HOME does not exist"
    exit 1
+fi
+
+if [ -f $MIDO_HOME/prepare-java ]; then
+    . $MIDO_HOME/prepare-java
+else
+    echo "$MIDO_HOME/prepare-java: file not found"
+    exit 1
 fi
 
 if [ -z "$MIDO_JAR" ]; then
diff --git a/midolman/src/deb/bin/mm-tests b/midolman/src/deb/bin/mm-tests
--- a/midolman/src/deb/bin/mm-tests
+++ b/midolman/src/deb/bin/mm-tests
@@ -17,10 +17,20 @@
 # some modules required in the kernel
 REQUIRED_MODS="openvswitch gre"
 
-if [ -f /usr/share/midolman/prepare-java ]; then
-    . /usr/share/midolman/prepare-java
+# If MIDO_HOME has not been set, set it.
+if [ -z "$MIDO_HOME" ]; then
+   MIDO_HOME=/usr/share/midolman
+fi
+
+if [ ! -d "$MIDO_HOME" ]; then
+   echo "ERROR: $MIDO_HOME does not exist"
+   exit 1
+fi
+
+if [ -f $MIDO_HOME/prepare-java ]; then
+    . $MIDO_HOME/prepare-java
 else
-    echo "/usr/share/midolman/prepare-java: file not found"
+    echo "$MIDO_HOME/prepare-java: file not found"
     exit 1
 fi
 
@@ -88,16 +98,6 @@ for MOD in $REQUIRED_MODS ; do
         modprobe -q $MOD 2>/dev/null
     fi
 done
-
-# If MIDO_HOME has not been set, set it.
-if [ -z "$MIDO_HOME" ]; then
-   MIDO_HOME=/usr/share/midolman
-fi
-
-if [ ! -d "$MIDO_HOME" ]; then
-   echo "ERROR: $MIDO_HOME does not exist"
-   exit 1
-fi
 
 JAVA_LIBRARY_PATH=-Djava.library.path=/lib:/usr/lib
 MIDO_DEP_CLASS_PATH=`echo $MIDO_HOME/dep/* | sed 's/ /:/g'`
