MidoNet: Update to JDK 1.8
Change-Id: Ic8de2ad1d865be00fdce887b84416a96ec1909be
Signed-off-by: Duarte Nunes <duarte@midokura.com>

diff --git a/midolman/src/deb/bin/mm-tests b/midolman/src/deb/bin/mm-tests
--- a/midolman/src/deb/bin/mm-tests
+++ b/midolman/src/deb/bin/mm-tests
@@ -17,11 +17,12 @@
 # some modules required in the kernel
 REQUIRED_MODS="openvswitch gre"
 
-# The first existing directory is used for JAVA_HOME if needed.
-JVM_SEARCH_DIRS="/usr/lib/jvm/java-7-openjdk-amd64 \
-                 /usr/lib/jvm/java-7-openjdk \
-                 /usr/lib/jvm/java-7-sun"
-
+if [ -f /usr/share/midolman/prepare-java ]; then
+    . /usr/share/midolman/prepare-java
+else
+    echo "/usr/share/midolman/prepare-java: file not found"
+    exit 1
+fi
 
 ##############################################################
 
@@ -88,34 +89,6 @@ for MOD in $REQUIRED_MODS ; do
     fi
 done
 
-# If JAVA_HOME has not been set, try to determine it.
-if [ -z "$JAVA_HOME" ]; then
-    # If java is in PATH, use a JAVA_HOME that corresponds to that. This is
-    # both consistent with how the upstream startup script works, and how
-    # Debian works (read: the use of alternatives to set a system JVM).
-    if [ -n "`which java`" ]; then
-        java=`which java`
-        # Dereference symlink(s)
-        while true; do
-            if [ -h "$java" ]; then
-                java=`readlink "$java"`
-                continue
-            fi
-            break
-        done
-        JAVA_HOME="`dirname $java`/../"
-    # No JAVA_HOME set and no java found in PATH, search for a JVM.
-    else
-        for jdir in $JVM_SEARCH_DIRS; do
-            if [ -x "$jdir/bin/java" ]; then
-                JAVA_HOME="$jdir"
-                break
-            fi
-        done
-    fi
-fi
-JAVA="$JAVA_HOME/bin/java"
-
 # If MIDO_HOME has not been set, set it.
 if [ -z "$MIDO_HOME" ]; then
    MIDO_HOME=/usr/share/midolman
@@ -127,7 +100,6 @@ if [ ! -d "$MIDO_HOME" ]; then
 fi
 
 JAVA_LIBRARY_PATH=-Djava.library.path=/lib:/usr/lib
-MIDO_BOOTSTRAP_JAR=`ls $MIDO_HOME/dep/midonet-jdk-bootstrap-*.jar`
 MIDO_DEP_CLASS_PATH=`echo $MIDO_HOME/dep/* | sed 's/ /:/g'`
 MIDO_JAR=`ls $MIDO_HOME/midolman-*.jar 2>/dev/null`
 if [ ! -e "$MIDO_JAR" -a -z "$MIDO_EXTRA_JARS" ] ; then
@@ -145,8 +117,7 @@ run_test() {
     shift
     echo "Running $MAIN"
     $JAVA -Dlogback.configurationFile=file:/etc/midolman/logback-dpctl.xml\
-        $JAVA_LIBRARY_PATH -Xbootclasspath/p:$MIDO_BOOTSTRAP_JAR\
-        -cp $CLASSPATH $MAIN $*
+        $JAVA_LIBRARY_PATH -cp $CLASSPATH $MAIN $*
     [ $? -eq 0 ] || abort "error when running $MAIN"
 }
 
