Port MDTS fixes from out-tree MDTS (sync)
While keeping the MDTS1 structure and scripts. This patch is a snapshot
of the current oss master branch with the latest additions up to commit
ace37f633ace2b889baa1a55ff72027f88eb996c (Prevent vtep from exiting
without agents up).

Change-Id: Ic167ac9a644b6e53ed8cd350c851151370d8946a

diff --git a/tests/mmm/scripts/start b/tests/mmm/scripts/start
--- a/tests/mmm/scripts/start
+++ b/tests/mmm/scripts/start
@@ -22,11 +22,25 @@
 (cd zookeeper && bash -x start)
 (cd cassandra && bash -x start)
 
-sleep 10
-
 (cd quagga && bash -x start)
 (cd dnsmasq && bash -x start)
 (cd midolman && bash -x start)
 
 (cd midonet-api && bash -x start)
-(cd midonet-cp && bash -x start)
+
+#Wait for agents to be registered before finishing start sequence
+RETRIES=30
+CONNECTED=false
+while [ $CONNECTED == "false" ]; do
+    if [ `midonet-cli --midonet-url http://localhost:8080/midonet-api -A -e "host list" | wc -l` -eq 3 ]; then
+        CONNECTED=true
+    elif [ $RETRIES -eq 0 ]; then
+        echo "Midolman hosts failed to start.  Midonet-API host list:"
+        midonet-cli --midonet-url http://localhost:8080/midonet-api -A -e "host list"
+        sudo ../../tools/logs/dump_per_suite_logs.sh
+        exit 1
+    else
+        (( RETRIES-- ))
+        sleep 5
+    fi
+done
