Port MDTS fixes from out-tree MDTS
While keeping the MDTS1 structure and scripts.  This patch removes non
relevant details from README.md, and maintains the bootstrap_v2 script
that was removed from the out-tree version.  mdts_cbt is also not kept
in the mdts1 version as the vast majority of the functionality provided
relates to managing multiple external dependencies accross mdts,
ci_tools, midonet, etc.  These are no longer relevant, since all code
required lives in-tree.

Change-Id: I295cab8c31c4ecd1265a95706fa2c837792c58ca
Signed-off-by: Galo Navarro <galo@midokura.com>

diff --git a/tests/mmm/scripts/zookeeper/start b/tests/mmm/scripts/zookeeper/start
--- a/tests/mmm/scripts/zookeeper/start
+++ b/tests/mmm/scripts/zookeeper/start
@@ -33,11 +33,20 @@ else
 fi
 
 # Checking Zookeeper status
-sleep 5
-echo Zookeeper 1
-echo ruok | nc 10.0.0.2 2181
-echo Zookeeper 2
-echo ruok | nc 10.0.0.3 2181
-echo Zookeeper 3
-echo ruok | nc 10.0.0.4 2181
-
+retries=0
+for i in 2 3 4
+do
+  echo "Zookeeper at ns00$i"
+  until echo ruok | nc 10.0.0.$i 2181 | grep imok
+  do
+    echo "Waiting for Zookeeper ns00$i to start"
+    sleep 1
+    ((retries++))
+    if [ $retries -gt 30 ]
+    then
+      echo "Could not start Zookeeper at ns00$i"
+      exit 1
+    fi
+  done
+  retries=0
+done
