MidoNet: Update to JDK 1.8
Change-Id: Ic8de2ad1d865be00fdce887b84416a96ec1909be
Signed-off-by: Duarte Nunes <duarte@midokura.com>

diff --git a/midolman/src/deb/init/midolman-start b/midolman/src/deb/init/midolman-start
--- a/midolman/src/deb/init/midolman-start
+++ b/midolman/src/deb/init/midolman-start
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -x
 
 # Copyright 2014 Midokura SARL
 #
@@ -29,6 +29,13 @@ MIDO_CFG_FILE=midolman.conf
 QUAGGA_DIR=/var/run/quagga
 WATCHDOG_TIMEOUT=10
 
+if [ -f /usr/share/midolman/prepare-java ]; then
+    . /usr/share/midolman/prepare-java
+else
+    echo "/usr/share/midolman/prepare-java: file not found"
+    exit 1
+fi
+
 if [ -f /etc/midolman/midolman-env.sh ]; then
     . /etc/midolman/midolman-env.sh
 else
@@ -36,55 +43,11 @@ else
     exit 1
 fi
 
-check_for_java7() {
-    [ "x" = "x$1" ] && return 1
-    [ -x "$1" ] || return 1
-    $1 -version 2>&1 | grep '^java version' | sed -e 's/^[^"]*"\(.*\)"$/\1/' \
-        | grep '^1.7.' >/dev/null 2>&1
-}
-
-if [ -n "`which java`" ]; then
-        java=`which java`
-        # Dereference symlink(s)
-        while true; do
-            if [ -h "$java" ]; then
-                java=`readlink "$java"`
-                continue
-            fi
-            break
-        done
-        JVM_SEARCH_DIRS="`dirname $java`/../ $JVM_SEARCH_DIRS"
-fi
-if [ ! -z "$JAVA_HOME" ]; then
-    JVM_SEARCH_DIRS="$JAVA_HOME $JVM_SEARCH_DIRS"
-fi
-
-oldopts=$-
-set +e
-JAVA_HOME=
-for jdir in $JVM_SEARCH_DIRS; do
-    check_for_java7 "$jdir/bin/java"
-    if [ $? -eq 0 ]; then
-        JAVA_HOME="$jdir"
-        break
-    fi
-done
-echo $oldopts | grep 'e' 2>&1 >/dev/null && set -e
-
-if [ -z "$JAVA_HOME" ] ; then
-    echo "No suitable JVM found (at least v1.7 required)"
-    exit 1
-fi
-
-JAVA="$JAVA_HOME/bin/java"
-
 MIDO_JAR=`ls $MIDO_HOME/midolman-*.jar`
 MIDO_DEP_CLASS_PATH=$MIDO_HOME/dep/*
-MIDO_BOOTSTRAP_JAR=`ls $MIDO_HOME/dep/midonet-jdk-bootstrap-*.jar`
 MIDO_MAIN=org.midonet.midolman.Midolman
 
 test -r $MIDO_JAR || exit 1
-test -r $MIDO_BOOTSTRAP_JAR || exit 1
 
 # OpenJDK uses the system jnidispatcher as default, since /usr/lib/jni is in
 # the java library path. We specify our jna.jar in the classpath, this leads
@@ -107,11 +70,10 @@ MIDO_WATCHDOG_TIMEOUT="${WATCHDOG_TIMEOUT:-10}"
 if [ -x /usr/bin/wdog ] && [ -z "$WATCHDOG_DISABLE" ] ; then
     exec /usr/bin/wdog -d /var/log/midolman $WATCHDOG_TIMEOUT -- \
                 $JAVA $JAVA_LIBRARY_PATH \
-                -Xbootclasspath/p:$MIDO_BOOTSTRAP_JAR \
                 -cp $MIDO_JAR:$MIDO_DEP_CLASS_PATH \
                 $JAVA_OPTS $MIDO_MAIN -c $MIDO_CFG/$MIDO_CFG_FILE
 else
-    exec $JAVA $JAVA_LIBRARY_PATH -Xbootclasspath/p:$MIDO_BOOTSTRAP_JAR \
+    exec $JAVA $JAVA_LIBRARY_PATH 
                 -cp $MIDO_JAR:$MIDO_DEP_CLASS_PATH \
                 $JAVA_OPTS $MIDO_MAIN -c $MIDO_CFG/$MIDO_CFG_FILE
 fi
