Packaging: introduce midonet-tools
Several changes come with it:

  * Jar dpeendencies are bundled in a fat jar for mm and -tools. Each package
    brings his own jar.
  * Jar lose the -version suffix.
  * mn-conf, mm-meter, mm-stat moved over to midonet-tools. On which midolman
    depends
  * Cleaned up and removed redundant dependencies all over the place.

Change-Id: Idb4f68ca22a9dae5439ff0566ec1df2db3946bf8
Signed-off-by: Guillermo Ontanon <guillermo@midokura.jp>

diff --git a/midonet-tools/src/bin/mm-meter b/midonet-tools/src/bin/mm-meter
--- a/midonet-tools/src/bin/mm-meter
+++ b/midonet-tools/src/bin/mm-meter
@@ -16,7 +16,7 @@
 
 # If MIDO_HOME has not been set, set it.
 if [ -z "$MIDO_HOME" ]; then
-   MIDO_HOME=/usr/share/midolman
+   MIDO_HOME=/usr/share/midonet-tools
 fi
 
 if [ ! -d "$MIDO_HOME" ]; then
@@ -31,8 +31,16 @@ else
     exit 1
 fi
 
-MAIN_CLASS='org.midonet.midolman.management.MidolmanStat'
-CLASSPATH=$MIDO_HOME/*:$MIDO_HOME/dep/*
+if [ -z "$MIDO_JAR" ]; then
+   MIDO_JAR=`ls $MIDO_HOME/midonet-tools.jar`
+fi
 
-exec $JAVA -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none \
-    -cp $CLASSPATH $MAIN_CLASS $*
+if [ ! -e "$MIDO_JAR" ]; then
+   echo "ERROR: $MIDO_JAR does not exist"
+   exit 1
+fi
+
+JAVA_LIBRARY_PATH=-Djava.library.path=/lib:/usr/lib
+
+exec $JAVA $JAVA_LIBRARY_PATH -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none \
+    -cp $MIDO_JAR org.midonet.management.MidolmanMeter $*
