Update devmido to use installShadowApp
This patch contains devmido adjustment to two recent changes in
midonet:

Commit 227d18cc5bb40bc2b33ccd1f4d98f610ea6ea24b moved mn-conf from
midolman to midonet-tools sub-project.

Commit a46e5ec8f2837965540ac8a1b6e35cb3ba728489 introduced a new way
to produce midolman and midonet-tools jars, which bundles all of their
dependent jars into one jar.

Update devmido so that mm-ctl, mm-dpctl and mn-conf proxy scripts point
to these new jars instead of creating a directory of the dependent
jars, for midolman and midonet-tools subprojects.

Fixes: MNA-875
Signed-off-by: Ryu Ishimoto <ryu@midokura.com>

Change-Id: I9699584fc8d2415b7530baa4abc9a68bb985bd5a

diff --git a/midonet-tools/src/bin/mn-conf b/midonet-tools/src/bin/mn-conf
--- a/midonet-tools/src/bin/mn-conf
+++ b/midonet-tools/src/bin/mn-conf
@@ -32,7 +32,18 @@ else
 fi
 
 MAIN_CLASS='org.midonet.conf.MidoConfTool'
-CLASSPATH=$MIDO_HOME/midonet-tools.jar
+
+# Allow overriding the default jar location 
+if [ -z "$MIDO_JAR" ]; then
+   CLASSPATH=$MIDO_HOME/midonet-tools.jar
+else
+   CLASSPATH=$MIDO_JAR
+fi
+
+if [ ! -e "$CLASSPATH" ]; then
+   echo "ERROR: $CLASSPATH is not set"
+   exit 1
+fi
 
 exec $JAVA -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none \
     -cp $CLASSPATH $MAIN_CLASS $*
