Clean up old namespace when restarting
When re-deploying an haproxy namespace, for example on
midolman restart, the haproxy script should gracefully
clean up anything left over from the old deployment.

Change-Id: I89c7d1ec451aab5c3048f1282fbd671911336cd3
Signed-off-by: Joe Mills <joe@midokura.com>

diff --git a/midolman/src/lib/midolman/service_containers/haproxy/haproxy-helper b/midolman/src/lib/midolman/service_containers/haproxy/haproxy-helper
--- a/midolman/src/lib/midolman/service_containers/haproxy/haproxy-helper
+++ b/midolman/src/lib/midolman/service_containers/haproxy/haproxy-helper
@@ -58,17 +58,46 @@ restart_ha() {
     ip netns exec $NAME haproxy -f $CONF
 }
 
-cleanns() {
-    if ! $(sudo ip netns | grep "^$NAME$" > /dev/null ); then
-        echo "Namespace $NAME doesn't exist";
-        exit 0
+checkns() {
+    if [ $retry -eq 0 ]; then
+        echo "Namespace failed to delete"
+        exit 1
     fi
-    for pid in $(ip netns pids $NAME)
-    do
-        kill -9 $pid
+    $((retry--))
+    sudo ip netns | grep "^$NAME$" > /dev/null
+}
+
+checklink() {
+    if [ $retry -eq 0 ]; then
+        echo "link failed to delete"
+        exit 1
+    fi
+    $((retry--))
+    grep -q " *$IFACE:" /proc/net/dev
+}
+
+cleanns() {
+    retry=10
+    if checkns; then
+        for pid in $(ip netns pids $NAME)
+        do
+            kill -9 $pid
+        done
+        ip netns del $NAME
+    fi
+
+    while checkns; do
+        sleep 1
     done
-    ip netns del $NAME
-    ip link del $IFACE
+
+    retry=10
+    if checklink; then
+        ip link del $IFACE
+    fi
+
+    while checklink; do
+        sleep 1
+    done
 }
 
 ACTION=$1
@@ -90,6 +119,8 @@ case $ACTION in
             echo "$0 makens NAME IFACE IP ROUTERIP"
             exit 1
         fi
+        # clean up anything left over from a previous deployment.
+        cleanns
         makens
         ;;
     restart_ha)
